WARN 2: [filename: 2_11_a_global_vars_should_be_commented_warning_.py, line: 3]: Global variable VAR1 has missing detailed comment for it
WARN 2: [filename: 2_11_a_global_vars_should_be_commented_warning_.py, line: 7]: Global variable VAR3 has missing detailed comment for it
WARN 2: [filename: 2_11_a_global_vars_should_be_commented_warning_.py, line: 9]: Global variable VAR4 has missing detailed comment for it
