WARN [filename: 2_11_a_global_vars_should_be_commented_warning_.py, line: 3, column: 0]: Detailed comments should be added to each global variable
WARN [filename: 2_11_a_global_vars_should_be_commented_warning_.py, line: 7, column: 0]: Detailed comments should be added to each global variable
WARN [filename: 2_11_a_global_vars_should_be_commented_warning_.py, line: 9, column: 0]: Detailed comments should be added to each global variable
