WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 3]: Comparison to none should be `var is None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 6]: Comparison to none should be `arg2 is not None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 8]: Comparison to none should be `b is None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 9]: Comparison to none should be `a is not None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 10]: Comparison to none should be `a is None`
