WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 3]: Should be `var is None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 6]: Should be `arg2 is not None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 8]: Should be `b is None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 9]: Should be `a is not None`
WARN 8: [filename: 4_1_compare_with_none_warning_.py, line: 10]: Should be `a is None`
