{"WARN": 8, "filename": "4_1_compare_with_none_warning_.py", "lineno": 3, "message": "Comparison to none should be `var is None`", "warnline": "if var == None :"}
{"WARN": 8, "filename": "4_1_compare_with_none_warning_.py", "lineno": 6, "message": "Comparison to none should be `arg2 is not None`", "warnline": "fn ( arg1 is not None , arg2 != None )"}
{"WARN": 8, "filename": "4_1_compare_with_none_warning_.py", "lineno": 8, "message": "Comparison to none should be `b is None`", "warnline": "a == b == None"}
{"WARN": 8, "filename": "4_1_compare_with_none_warning_.py", "lineno": 9, "message": "Comparison to none should be `a is not None`", "warnline": "a != None"}
{"WARN": 8, "filename": "4_1_compare_with_none_warning_.py", "lineno": 10, "message": "Comparison to none should be `a is None`", "warnline": "None == a"}
