{"WARN": 4, "filename": "3_2_class_name_naming_warning_.py", "lineno": 4, "message": "Invalid class name: simple_class", "warnline": "class simple_class :"}
{"WARN": 4, "filename": "3_2_class_name_naming_warning_.py", "lineno": 6, "message": "Invalid class name: subclass", "warnline": "  class subclass :"}
{"WARN": 4, "filename": "3_2_class_name_naming_warning_.py", "lineno": 11, "message": "Invalid class name: formatted_class_def", "warnline": "class  \\ formatted_class_def :"}
