{"WARN": 5, "filename": "3_3_func_naming_warning_.py", "lineno": 4, "message": "Invalid function name: invalidTopLevel", "warnline": "def invalidTopLevel ( ) :"}
{"WARN": 5, "filename": "3_3_func_naming_warning_.py", "lineno": 6, "message": "Invalid function name: invalidInner", "warnline": "  def invalidInner ( ) :"}
{"WARN": 5, "filename": "3_3_func_naming_warning_.py", "lineno": 22, "message": "Invalid function name: invalidPublic", "warnline": "  def invalidPublic ( self ) :"}
{"WARN": 5, "filename": "3_3_func_naming_warning_.py", "lineno": 28, "message": "Invalid function name: _invalidProtected", "warnline": "  def _invalidProtected ( self ) :"}
{"WARN": 5, "filename": "3_3_func_naming_warning_.py", "lineno": 34, "message": "Invalid function name: __invalidPrivate", "warnline": "  def __invalidPrivate ( self ) :"}
