{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "lineno": 5, "message": "Invalid variable name: PascalCaseVar", "warnline": "PascalCaseVar = 0"}
{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "lineno": 9, "message": "Invalid variable name: FirstArg", "warnline": "def func ( FirstArg , second_var ) :"}
{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "lineno": 10, "message": "Invalid variable name: LocalVar1", "warnline": "  LocalVar1 = FirstVar"}
{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "lineno": 16, "message": "Invalid variable name: NotSoSpecialFiled", "warnline": "  NotSoSpecialFiled = 0"}
