{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "line": 5, "message": "Invalid variable name: PascalCaseVar"}
{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "line": 9, "message": "Invalid variable name: FirstArg"}
{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "line": 10, "message": "Invalid variable name: LocalVar1"}
{"WARN": 6, "filename": "3_4_variable_names_warning_.py", "line": 16, "message": "Invalid variable name: NotSoSpecialFiled"}
