WARN 6: [filename: 3_4_variable_names_warning_.py, line: 5, column: 0]: Invalid variable name: PascalCaseVar
WARN 6: [filename: 3_4_variable_names_warning_.py, line: 8, column: 9]: Invalid variable name: FirstArg
WARN 6: [filename: 3_4_variable_names_warning_.py, line: 9, column: 4]: Invalid variable name: LocalVar1
WARN 6: [filename: 3_4_variable_names_warning_.py, line: 15, column: 4]: Invalid variable name: NotSoSpecialFiled
